on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        
      - name: Deploy Native Modules
        uses: HubSpot/hubspot-cms-deploy-action@v1.6
        with:
          src_dir: src/native
          dest_dir: /
          portal_id: ${{ secrets.HUBSPOT_PORTAL_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
